[categories]
equity
fixed_income
foreign
domestic
small
mid
large
pme
reit
cash


# Each entity can be a member of at most one category from each rule
[exclusive]
equity, fixed_income, cash
foreign, domestic
small, mid, large


# Each entity must be a member of at least one category from each rule
[exhaustive]
equity, fixed_income, cash
foreign, domestic
small, mid, large


